### ISSUE TITLE
dein

### ISSUE THREAD

**Issue by lifala71** [mattn/livestyle-vim#12]
possible install with dein ?

**Comment by lifala71** [comment]
:LiveStyle                                                                                             
Erreur détectée en traitant function livestyle#setup[16]..<SNR>112_do_post[4]..provider#python#Call :  
ligne   18 :                                                                                           
Traceback (most recent call last):                                                                     
  File "<string>", line 1, in <module>                                                                 
  File "/usr/lib64/python2.7/urllib.py", line 89, in urlopen                                           
    return opener.open(url, data)                                                                      
  File "/usr/lib64/python2.7/urllib.py", line 215, in open                                             
    return getattr(self, name)(url, data)                                                              
  File "/usr/lib64/python2.7/urllib.py", line 350, in open_http                                        
    h.endheaders(data)                                                                                 
  File "/usr/lib64/python2.7/httplib.py", line 1038, in endheaders                                     
    self._send_output(message_body)                                                                    
  File "/usr/lib64/python2.7/httplib.py", line 882, in _send_output                                    
    self.send(msg)                                                                                     
  File "/usr/lib64/python2.7/httplib.py", line 844, in send                                            
    self.connect()                                                                                     
  File "/usr/lib64/python2.7/httplib.py", line 821, in connect                                         
    self.timeout, self.source_address)                                                                 
  File "/usr/lib64/python2.7/socket.py", line 575, in create_connection                                
    raise err                                                                                          
IOError: [Errno socket error] [Errno 111] Connection refused                                           
Erreur détectée en traitant function livestyle#setup[20]..<SNR>112_do_post[4]..provider#python#Call :  
ligne   18 :                                                                                           
Traceback (most recent call last):                                                                     
  File "<string>", line 1, in <module>                                                                 
  File "/usr/lib64/python2.7/urllib.py", line 89, in urlopen                                           
    return opener.open(url, data)                                                                      
  File "/usr/lib64/python2.7/urllib.py", line 215, in open                                             
    return getattr(self, name)(url, data)                                                              
  File "/usr/lib64/python2.7/urllib.py", line 350, in open_http                                        
    h.endheaders(data)                                                                                 
  File "/usr/lib64/python2.7/httplib.py", line 1038, in endheaders                                     
    self._send_output(message_body)                                                                    
  File "/usr/lib64/python2.7/httplib.py", line 882, in _send_output                                    
    self.send(msg)                                                                                     
  File "/usr/lib64/python2.7/httplib.py", line 844, in send                                            
    self.connect()                                                                                     
  File "/usr/lib64/python2.7/httplib.py", line 821, in connect                                         
    self.timeout, self.source_address)                                                                 
  File "/usr/lib64/python2.7/socket.py", line 575, in create_connection                                
    raise err                                                                                          
IOError: [Errno socket error] [Errno 111] Connection refused
